### PR TITLE
Perform in memory reorg before validating a block in a branch

### LINKED ISSUE #752: Working reorgs with "verify stakes unspent" (to be able to detect/tolerate double-spends from other branches)
Using utxo set inside the `ChainstateRef::check_block_header` to validate consensus is incorrect.

It's prone to the attacks described in this topic:
https://medium.com/@dsl_uiuc/fake-stake-attacks-on-chain-based-proof-of-stake-cryptocurrencies-b8b05723f806

A possible solution would be to store spent stakes in a separate collection. Then for every branch recreate a temporary state from common ancestor block where we check that a stake output is either in utxo set or wasn't spent in that ancestor or current branch.

### PR DESCRIPTION
**Pull request by azarovh**
To validate a block with PoS in a branch we need a utxo set and accounting data to be up to that particular point in history and not the mainchain tip. So suggested solution is to perform in memory reorg and use the resulting data to validate a block. It's slow but relatively simple.

Regarding the speed if measuring the time of the `syncing_test::get_headers_branching_chains` test in debug with reorg depths of 1000 blocks the time is ~200s vs ~10s for prev version.  

Benchmark shows the time of 16.706s for 1000 blocks

Fixes #752

### CODE REVIEW

File: chainstate/src/detail/chainstateref/mod.rs [hunk 1]
```diff
@@ -762,6 +778,131 @@ impl<'a, S: BlockchainStorageRead, V: TransactionVerificationStrategy> Chainstat
             .collect();
         Ok(result)
     }
+
+    // Disconnect all blocks from the mainchain up until common ancestor of provided block
+    // and then connect all block in the new branch.
+    // All these operations are performed via `TransactionVerifier` without db modifications
+    // and the resulting delta is returned.
+    pub fn reorganize_in_memory(
```
Comment (TheQuantumPhysicist) [inline chainstate/src/detail/chainstateref/mod.rs:786]: Please move this to a submodule. In the future we'll try to abstract this in a better way.

File: chainstate/src/detail/chainstateref/mod.rs [hunk 2]
```diff
@@ -428,36 +427,54 @@ impl<'a, S: BlockchainStorageRead, V: TransactionVerificationStrategy> Chainstat
...
 
-        // TODO(Gosha):
-        // using utxo set like this is incorrect, because it represents the state of the mainchain, so it won't
-        // work when checking blocks from branches. See mintlayer/mintlayer-core/issues/752 for details
         let utxos_db = UtxosDB::new(&self.db_tx);
         let pos_db = PoSAccountingDB::<_, TipStorageTag>::new(&self.db_tx);
+
+        let best_block_id = self.get_best_block_id()?;
+        let (utxos_cache, pos_delta, epoch_data_cache) = if best_block_id == *header.prev_block_id()
+        {
```
Comment (TheQuantumPhysicist) [inline chainstate/src/detail/chainstateref/mod.rs:439]: There's a question on whether this is necessary. Ideally speaking, the "reorg_in_memory" function would be a no-op is best_block == previous_block. Is it possible to achieve that?

File: chainstate/src/detail/chainstateref/mod.rs [hunk 3]
```diff
@@ -428,36 +427,54 @@ impl<'a, S: BlockchainStorageRead, V: TransactionVerificationStrategy> Chainstat
...
         self.enforce_checkpoints(header).log_err()?;
 
-        // TODO(Gosha):
-        // using utxo set like this is incorrect, because it represents the state of the mainchain, so it won't
-        // work when checking blocks from branches. See mintlayer/mintlayer-core/issues/752 for details
         let utxos_db = UtxosDB::new(&self.db_tx);
         let pos_db = PoSAccountingDB::<_, TipStorageTag>::new(&self.db_tx);
+
+        let best_block_id = self.get_best_block_id()?;
+        let (utxos_cache, pos_delta, epoch_data_cache) = if best_block_id == *header.prev_block_id()
```
Comment (TheQuantumPhysicist) [inline chainstate/src/detail/chainstateref/mod.rs:438]: Keep in mind that this reorging is only necessary for select types of consensus. Perhaps we should wrap this whole thing with a boolean derived from ConsensusData, where it's only true for PoS. We don't need to reorg for PoW.

File: chainstate/tx-verifier/src/transaction_verifier/mod.rs [hunk 4]
```diff
@@ -91,10 +91,10 @@ pub struct Subsidy(pub Amount);
 #[derive(Debug, Eq, PartialEq)]
 pub struct TransactionVerifierDelta {
     tx_index_cache: BTreeMap<OutPointSourceId, CachedInputsOperation>,
-    utxo_cache: ConsumedUtxoCache,
+    pub utxo_cache: ConsumedUtxoCache,
```
Comment (TheQuantumPhysicist) [inline chainstate/tx-verifier/src/transaction_verifier/mod.rs:94]: No pub, please.

File: chainstate/src/detail/chainstateref/mod.rs (hunk 2 above)
Comment (azarovh) [reply chainstate/src/detail/chainstateref/mod.rs:439]: actually it's already working as you described I just thought that it was a good check to avoid unnecessary computation

**Review by TheQuantumPhysicist — APPROVED** [review]
I don't see big issues. Good work. The only problem I see is the duplication, and I'd like (in the future) to unify reorging both in memory and in a database transaction such that we can just choose to keep it or persist it, instead of doing it twice.

**Comment by azarovh** [comment]
>  I'd like (in the future) to unify reorging both in memory and in a database transaction

I tried to do that at first but then it just got too complicated, so I took this approach which was easier and more isolated

**Comment by TheQuantumPhysicist** [comment]
> >  I'd like (in the future) to unify reorging both in memory and in a database transaction
> 
> I tried to do that at first but then it just got too complicated, so I took this approach which was easier and more isolated

And hence "future" :)

Please create an issue for it

File: chainstate/src/detail/chainstateref/mod.rs (hunk 1 above)
Comment (azarovh) [reply chainstate/src/detail/chainstateref/mod.rs]: done

File: chainstate/src/detail/chainstateref/mod.rs (hunk 2 above)
Comment (azarovh) [reply chainstate/src/detail/chainstateref/mod.rs]: removed the check

File: chainstate/src/detail/chainstateref/mod.rs (hunk 3 above)
Comment (azarovh) [reply chainstate/src/detail/chainstateref/mod.rs]: added check for pos

**Review by muursh — APPROVED** [review]
Looks fine overall to me

**Review by iljakuklic — APPROVED** [review]
